// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.SEServer.GameData.Resolvers
{
    public class GeneratedGameDataResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedGameDataResolver();

        private GeneratedGameDataResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedGameDataResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedGameDataResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedGameDataResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(19)
            {
                { typeof(global::System.Collections.Generic.Queue<global::SEServer.Data.Message.NotifyData>), 0 },
                { typeof(global::System.Collections.Generic.Queue<global::SEServer.Data.Message.SubmitData>), 1 },
                { typeof(global::SEServer.GameData.GraphType), 2 },
                { typeof(global::SEServer.Data.CId), 3 },
                { typeof(global::SEServer.Data.EId), 4 },
                { typeof(global::SEServer.Data.Message.NotifyData), 5 },
                { typeof(global::SEServer.Data.Message.SubmitData), 6 },
                { typeof(global::SEServer.Data.PlayerId), 7 },
                { typeof(global::SEServer.Data.SVector2), 8 },
                { typeof(global::SEServer.GameData.Component.GraphComponent), 9 },
                { typeof(global::SEServer.GameData.Component.MoveInputComponent), 10 },
                { typeof(global::SEServer.GameData.Component.PlayerComponent), 11 },
                { typeof(global::SEServer.GameData.Component.PlayerNotifyComponent), 12 },
                { typeof(global::SEServer.GameData.Component.PlayerNotifyGlobalComponent), 13 },
                { typeof(global::SEServer.GameData.Component.PlayerSubmitComponent), 14 },
                { typeof(global::SEServer.GameData.Component.PlayerSubmitGlobalComponent), 15 },
                { typeof(global::SEServer.GameData.Component.PropertyComponent), 16 },
                { typeof(global::SEServer.GameData.Component.ShootInputComponent), 17 },
                { typeof(global::SEServer.GameData.Component.TransformComponent), 18 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.QueueFormatter<global::SEServer.Data.Message.NotifyData>();
                case 1: return new global::MessagePack.Formatters.QueueFormatter<global::SEServer.Data.Message.SubmitData>();
                case 2: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.GraphTypeFormatter();
                case 3: return new MessagePack.SEServer.GameData.Formatters.SEServer.Data.CIdFormatter();
                case 4: return new MessagePack.SEServer.GameData.Formatters.SEServer.Data.EIdFormatter();
                case 5: return new MessagePack.SEServer.GameData.Formatters.SEServer.Data.Message.NotifyDataFormatter();
                case 6: return new MessagePack.SEServer.GameData.Formatters.SEServer.Data.Message.SubmitDataFormatter();
                case 7: return new MessagePack.SEServer.GameData.Formatters.SEServer.Data.PlayerIdFormatter();
                case 8: return new MessagePack.SEServer.GameData.Formatters.SEServer.Data.SVector2Formatter();
                case 9: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.GraphComponentFormatter();
                case 10: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.MoveInputComponentFormatter();
                case 11: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.PlayerComponentFormatter();
                case 12: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.PlayerNotifyComponentFormatter();
                case 13: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.PlayerNotifyGlobalComponentFormatter();
                case 14: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.PlayerSubmitComponentFormatter();
                case 15: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.PlayerSubmitGlobalComponentFormatter();
                case 16: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.PropertyComponentFormatter();
                case 17: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.ShootInputComponentFormatter();
                case 18: return new MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component.TransformComponentFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name


// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.SEServer.GameData.Formatters.SEServer.GameData
{

    public sealed class GraphTypeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.GraphType>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.GraphType value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((global::System.Int32)value);
        }

        public global::SEServer.GameData.GraphType Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::SEServer.GameData.GraphType)reader.ReadInt32();
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name



// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.SEServer.GameData.Formatters.SEServer.Data
{
    public sealed class CIdFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.Data.CId>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.Data.CId value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(1);
            writer.Write(value.Id);
        }

        public global::SEServer.Data.CId Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.Data.CId();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class EIdFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.Data.EId>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.Data.EId value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(1);
            writer.Write(value.Id);
        }

        public global::SEServer.Data.EId Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.Data.EId();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerIdFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.Data.PlayerId>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.Data.PlayerId value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(1);
            writer.Write(value.Id);
        }

        public global::SEServer.Data.PlayerId Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.Data.PlayerId();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SVector2Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.Data.SVector2>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.Data.SVector2 value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(2);
            writer.Write(value.X);
            writer.Write(value.Y);
        }

        public global::SEServer.Data.SVector2 Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var __X__ = default(float);
            var __Y__ = default(float);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __X__ = reader.ReadSingle();
                        break;
                    case 1:
                        __Y__ = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::SEServer.Data.SVector2(__X__, __Y__);
            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.SEServer.GameData.Formatters.SEServer.Data.Message
{
    public sealed class NotifyDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.Data.Message.NotifyData>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.Data.Message.NotifyData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.Type);
            writer.Write(value.Arg0);
            writer.Write(value.Arg1);
            writer.Write(value.Arg2);
            writer.Write(value.Arg3);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Info, options);
            writer.Write(value.Data);
        }

        public global::SEServer.Data.Message.NotifyData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.Data.Message.NotifyData();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Type = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Arg0 = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.Arg1 = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.Arg2 = reader.ReadInt32();
                        break;
                    case 4:
                        ____result.Arg3 = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.Info = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 6:
                        ____result.Data = global::MessagePack.Internal.CodeGenHelpers.GetArrayFromNullableSequence(reader.ReadBytes());
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SubmitDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.Data.Message.SubmitData>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.Data.Message.SubmitData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.Type);
            writer.Write(value.Arg0);
            writer.Write(value.Arg1);
            writer.Write(value.Arg2);
            writer.Write(value.Arg3);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Info, options);
            writer.Write(value.Data);
        }

        public global::SEServer.Data.Message.SubmitData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.Data.Message.SubmitData();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Type = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Arg0 = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.Arg1 = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.Arg2 = reader.ReadInt32();
                        break;
                    case 4:
                        ____result.Arg3 = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.Info = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 6:
                        ____result.Data = global::MessagePack.Internal.CodeGenHelpers.GetArrayFromNullableSequence(reader.ReadBytes());
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.SEServer.GameData.Formatters.SEServer.GameData.Component
{
    public sealed class GraphComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.GraphComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.GraphComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.GameData.GraphType>(formatterResolver).Serialize(ref writer, value.Type, options);
        }

        public global::SEServer.GameData.Component.GraphComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.GraphComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Type = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.GameData.GraphType>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class MoveInputComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.MoveInputComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.MoveInputComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Serialize(ref writer, value.Owner, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.SVector2>(formatterResolver).Serialize(ref writer, value.Input, options);
            writer.Write(value.TargetRotation);
        }

        public global::SEServer.GameData.Component.MoveInputComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.MoveInputComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Owner = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Input = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.SVector2>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.TargetRotation = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.PlayerComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.PlayerComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            writer.Write(value.PlayerId);
        }

        public global::SEServer.GameData.Component.PlayerComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.PlayerComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.PlayerId = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerNotifyComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.PlayerNotifyComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.PlayerNotifyComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Serialize(ref writer, value.Owner, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.NotifyData>>(formatterResolver).Serialize(ref writer, value.NotifyMessages, options);
        }

        public global::SEServer.GameData.Component.PlayerNotifyComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.PlayerNotifyComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Owner = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.NotifyMessages = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.NotifyData>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerNotifyGlobalComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.PlayerNotifyGlobalComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.PlayerNotifyGlobalComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Serialize(ref writer, value.Owner, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.NotifyData>>(formatterResolver).Serialize(ref writer, value.NotifyMessages, options);
        }

        public global::SEServer.GameData.Component.PlayerNotifyGlobalComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.PlayerNotifyGlobalComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Owner = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.NotifyMessages = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.NotifyData>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerSubmitComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.PlayerSubmitComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.PlayerSubmitComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            writer.WriteNil();
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Serialize(ref writer, value.Owner, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.SubmitData>>(formatterResolver).Serialize(ref writer, value.SubmitMessages, options);
        }

        public global::SEServer.GameData.Component.PlayerSubmitComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.PlayerSubmitComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Owner = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.SubmitMessages = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.SubmitData>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerSubmitGlobalComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.PlayerSubmitGlobalComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.PlayerSubmitGlobalComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            writer.WriteNil();
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Serialize(ref writer, value.Owner, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.SubmitData>>(formatterResolver).Serialize(ref writer, value.SubmitMessages, options);
        }

        public global::SEServer.GameData.Component.PlayerSubmitGlobalComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.PlayerSubmitGlobalComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Owner = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.SubmitMessages = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.Queue<global::SEServer.Data.Message.SubmitData>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PropertyComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.PropertyComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.PropertyComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            writer.Write(value.Speed);
            writer.Write(value.TargetAimRotation);
            writer.Write(value.Hp);
        }

        public global::SEServer.GameData.Component.PropertyComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.PropertyComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Speed = reader.ReadSingle();
                        break;
                    case 3:
                        ____result.TargetAimRotation = reader.ReadSingle();
                        break;
                    case 4:
                        ____result.Hp = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class ShootInputComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.ShootInputComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.ShootInputComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Serialize(ref writer, value.Owner, options);
            writer.Write(value.TriggerShoot);
        }

        public global::SEServer.GameData.Component.ShootInputComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.ShootInputComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Owner = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.PlayerId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.TriggerShoot = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class TransformComponentFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SEServer.GameData.Component.TransformComponent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SEServer.GameData.Component.TransformComponent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Serialize(ref writer, value.Id, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Serialize(ref writer, value.EntityId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.SVector2>(formatterResolver).Serialize(ref writer, value.Position, options);
            writer.Write(value.Rotation);
        }

        public global::SEServer.GameData.Component.TransformComponent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SEServer.GameData.Component.TransformComponent();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.CId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.EntityId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.EId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Position = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SEServer.Data.SVector2>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Rotation = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

